# Generated by Django 6.0.5 on 2026-06-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_p_rendez__f599ce_idx',
            old_name='paiement_rdv_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_p_statut_b61122_idx',
            old_name='paiement_statut_idx',
        ),
    ]
