# Generated by Django 6.0.5 on 2026-07-02 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_rename_paiement_rdv_statut_idx_paiements_p_rendez__f599ce_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(blank=True, choices=[('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money'), ('MPESA', 'M-Pesa'), ('AFRICELL_MONEY', 'Africell Money'), ('SUR_PLACE', 'Paiement sur place')], default='', max_length=20, verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PAYE_EN_LIGNE', 'Payé en ligne'), ('PAYE_SUR_PLACE', 'Payé sur place'), ('ANNULE', 'Annulé'), ('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé (ancien)'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='NON_PAYE', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(max_length=40, unique=True, verbose_name='Numéro de facture')),
                ('service', models.CharField(max_length=120, verbose_name='Service')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (CDF)')),
                ('mode_paiement', models.CharField(max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('GENEREE', 'Générée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='GENEREE', max_length=20, verbose_name='Statut')),
                ('devise', models.CharField(default='CDF', max_length=8, verbose_name='Devise')),
                ('preuve_paiement', models.CharField(blank=True, default='', max_length=255, verbose_name='Preuve de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('coiffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_coiffeur', to=settings.AUTH_USER_MODEL, verbose_name='Coiffeur')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.paiement', verbose_name='Paiement source')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='paiements_f_client__2b9be1_idx'), models.Index(fields=['coiffeur', '-created_at'], name='paiements_f_coiffeu_73d6b4_idx'), models.Index(fields=['statut'], name='paiements_f_statut_ef60b1_idx')],
            },
        ),
    ]
