# Generated by Django 6.0.5 on 2026-06-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='avis',
            new_name='avis_avis_coiffeu_317373_idx',
            old_name='avis_coiffeur_note_idx',
        ),
        migrations.RenameIndex(
            model_name='avis',
            new_name='avis_avis_signale_bbe92d_idx',
            old_name='avis_signale_idx',
        ),
    ]
