# Generated by Django 6.0.5 on 2026-05-07 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('coiffeur', models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('coiffeur', models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_prestation', models.CharField(max_length=100)),
                ('nom_salon', models.CharField(default='Mon Salon', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoiffeurService',
            fields=[
                ('id_coiffeur_service', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coiffeur', models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coiffeurs_lies', to='services.service')),
            ],
            options={
                'verbose_name': 'Service par Coiffeur',
                'verbose_name_plural': 'Services par Coiffeurs',
                'unique_together': {('service', 'coiffeur')},
            },
        ),
    ]
