# Generated by Django 6.0.5 on 2026-05-07 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_avis_options_avis_date_creation_alter_avis_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaire',
            options={'ordering': ['jour_semaine', 'heure_debut']},
        ),
        migrations.AlterField(
            model_name='horaire',
            name='coiffeur',
            field=models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='jour_semaine',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')]),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('client', 'coiffeur')},
        ),
        migrations.AlterUniqueTogether(
            name='horaire',
            unique_together={('coiffeur', 'jour_semaine')},
        ),
    ]
