# Generated by Django 6.0.5 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disponibiliteexception',
            new_name='planning_di_coiffeu_ecd5ca_idx',
            old_name='dispo_except_coiffeur_date_idx',
        ),
        migrations.RenameIndex(
            model_name='horaire',
            new_name='planning_ho_coiffeu_e1a25e_idx',
            old_name='horaires_coiffeur_jour_idx',
        ),
        migrations.AlterField(
            model_name='disponibiliteexception',
            name='disponible',
            field=models.BooleanField(default=False, help_text='False = indisponible (congé, maladie…). True = exceptionnellement ouvert.', verbose_name='Disponible ce jour-là'),
        ),
    ]
