# Generated by Django 6.0.5 on 2026-06-14 11:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Icône (emoji)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_prestation', models.CharField(max_length=100, verbose_name='Nom de la prestation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duree_minutes', models.PositiveIntegerField(help_text='Durée en minutes. Min 5 min, max 8h.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='Durée (minutes)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix (€)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image principale')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente de validation')], default='actif', max_length=20, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.categorieservice', verbose_name='Catégorie')),
                ('coiffeur', models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='services_proposes', to=settings.AUTH_USER_MODEL, verbose_name='Coiffeur')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='services/galerie/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='services.service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de service',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['coiffeur', 'statut'], name='services_se_coiffeu_265af0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['categorie', 'statut'], name='services_se_categor_882cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['actif'], name='services_se_actif_5c460f_idx'),
        ),
    ]
