# Generated by Codex on 2026-07-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='services/images/%Y/%m/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])],
                verbose_name='Image principale',
            ),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(
                upload_to='services/galerie/%Y/%m/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])],
                verbose_name='Image de galerie',
            ),
        ),
    ]
