# Generated by Django 6.0.5 on 2026-07-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image_and_gallery_to_local_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image principale'),
        ),
    ]
