# Generated by Django 6.0.5 on 2026-06-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfoliomedia',
            new_name='media_portf_coiffeu_de837a_idx',
            old_name='portfolio_coiffeur_ordre_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliomedia',
            new_name='media_portf_signale_6b9e8f_idx',
            old_name='portfolio_signale_idx',
        ),
    ]
