# Generated by Django 6.0.5 on 2026-07-02 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReactivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reactivation_traitees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reactivation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de réactivation',
                'verbose_name_plural': 'Demandes de réactivation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', '-created_at'], name='administrat_statut_7f0540_idx'), models.Index(fields=['utilisateur', '-created_at'], name='administrat_utilisa_bba523_idx')],
            },
        ),
    ]
