# Generated by Django 6.0.5 on 2026-06-30 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_seed_plans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='abonnementutilisateur',
            new_name='abonnements_coiffeu_4b9e7d_idx',
            old_name='abonnements_coiffeu_idx',
        ),
        migrations.RenameIndex(
            model_name='abonnementutilisateur',
            new_name='abonnements_date_fi_2c91d7_idx',
            old_name='abonnements_datefin_idx',
        ),
        migrations.AlterField(
            model_name='abonnementplan',
            name='avantages',
            field=models.TextField(blank=True, help_text='Un avantage par ligne — affiché sous forme de liste à puces côté frontend.', null=True, verbose_name='Avantages'),
        ),
        migrations.AlterField(
            model_name='abonnementplan',
            name='duree_mois',
            field=models.PositiveIntegerField(default=1, help_text="Durée d'un cycle de facturation, en mois.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (mois)'),
        ),
        migrations.AlterField(
            model_name='abonnementplan',
            name='mise_en_avant_priorite',
            field=models.PositiveIntegerField(default=0, help_text='Plus la valeur est élevée, plus les services du coiffeur sont mis en avant dans les listings clients.', verbose_name='Priorité de mise en avant'),
        ),
        migrations.AlterField(
            model_name='abonnementutilisateur',
            name='abonnement_plan',
            field=models.ForeignKey(blank=True, help_text="Null pendant une période d'essai sans plan payant choisi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscriptions', to='abonnements.abonnementplan', verbose_name='Plan souscrit'),
        ),
    ]
