# Generated by Django 6.0.5 on 2026-06-30 09:30

from django.db import migrations, models


def _index_names(connection, table_name):
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)
    return {name for name, info in constraints.items() if info.get('index')}


def _ensure_index(schema_editor, model, old_name, new_name, fields):
    existing = _index_names(schema_editor.connection, model._meta.db_table)
    new_index = models.Index(fields=fields, name=new_name)
    old_index = models.Index(fields=fields, name=old_name)

    if new_name in existing:
        return

    if old_name in existing:
        try:
            schema_editor.rename_index(model, old_index, new_index)
            return
        except Exception:
            try:
                schema_editor.remove_index(model, old_index)
            except Exception:
                pass

    schema_editor.add_index(model, new_index)


def _restore_index(schema_editor, model, old_name, new_name, fields):
    existing = _index_names(schema_editor.connection, model._meta.db_table)
    new_index = models.Index(fields=fields, name=new_name)
    old_index = models.Index(fields=fields, name=old_name)

    if old_name in existing:
        return

    if new_name in existing:
        try:
            schema_editor.rename_index(model, new_index, old_index)
            return
        except Exception:
            try:
                schema_editor.remove_index(model, new_index)
            except Exception:
                pass

    schema_editor.add_index(model, old_index)


def forwards(apps, schema_editor):
    RendezVous = apps.get_model('rendez_vous', 'RendezVous')
    _ensure_index(schema_editor, RendezVous, 'rdv_coiffeur_statut_idx', 'rendez_vous_coiffeu_25cbef_idx', ['coiffeur', 'statut'])
    _ensure_index(schema_editor, RendezVous, 'rdv_client_statut_idx', 'rendez_vous_client__7b39c6_idx', ['client', 'statut'])
    _ensure_index(schema_editor, RendezVous, 'rdv_date_debut_idx', 'rendez_vous_date_he_833195_idx', ['date_heure_debut'])


def backwards(apps, schema_editor):
    RendezVous = apps.get_model('rendez_vous', 'RendezVous')
    _restore_index(schema_editor, RendezVous, 'rdv_coiffeur_statut_idx', 'rendez_vous_coiffeu_25cbef_idx', ['coiffeur', 'statut'])
    _restore_index(schema_editor, RendezVous, 'rdv_client_statut_idx', 'rendez_vous_client__7b39c6_idx', ['client', 'statut'])
    _restore_index(schema_editor, RendezVous, 'rdv_date_debut_idx', 'rendez_vous_date_he_833195_idx', ['date_heure_debut'])


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_legacy_schema_fix'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, backwards),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='rendezvous',
                    new_name='rendez_vous_coiffeu_25cbef_idx',
                    old_name='rdv_coiffeur_statut_idx',
                ),
                migrations.RenameIndex(
                    model_name='rendezvous',
                    new_name='rendez_vous_client__7b39c6_idx',
                    old_name='rdv_client_statut_idx',
                ),
                migrations.RenameIndex(
                    model_name='rendezvous',
                    new_name='rendez_vous_date_he_833195_idx',
                    old_name='rdv_date_debut_idx',
                ),
                migrations.AlterField(
                    model_name='rendezvous',
                    name='statut',
                    field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
                ),
            ],
        ),
    ]
