# Generated by Django 6.0.5 on 2026-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0004_rename_rdv_coiffeur_statut_idx_rendez_vous_coiffeu_25cbef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut_paiement',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PAYE_EN_LIGNE', 'Payé en ligne'), ('PAYE_SUR_PLACE', 'Payé sur place'), ('ANNULE', 'Annulé')], default='NON_PAYE', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
