# Generated by Django 6.0.5 on 2026-05-07 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_horaire_options_alter_horaire_coiffeur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('statut', models.CharField(default='NON_LU', max_length=20)),
                ('type_notification', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_faites', to=settings.AUTH_USER_MODEL)),
                ('coiffeur', models.ForeignKey(limit_choices_to={'role': 'COIFFEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_associes', to='rendez_vous.rendezvous')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
            options={
                'verbose_name': 'Service du Rendez-vous',
            },
        ),
    ]
