# Generated by Django 6.0.5 on 2026-06-14 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu')], default='NON_LU', max_length=10)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('AVERTISSEMENT', 'Avertissement'), ('DANGER', 'Danger'), ('SYSTEME', 'Système')], default='INFO', max_length=20)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', '-created_at'], name='notificatio_utilisa_0877c3_idx')],
            },
        ),
    ]
