# Generated by Django 6.0.5 on 2026-06-28 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoris_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_service', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='favoris_fav_client__f80d34_idx'), models.Index(fields=['service', 'created_at'], name='favoris_fav_service_eda28b_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'service'), name='uniq_favori_client_service')],
            },
        ),
    ]
