# Generated by Django 6.0.5 on 2026-06-14 11:07

import authentification.models.utilisateur
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('COIFFEUR', 'Coiffeur'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BANNI', 'Banni')], default='EN_ATTENTE', max_length=20)),
                ('email_verifie', models.BooleanField(default=False)),
                ('deux_facteurs_actif', models.BooleanField(default=False)),
                ('tentatives_connexion', models.PositiveIntegerField(default=0)),
                ('verrouille_jusqua', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', authentification.models.utilisateur.UtilisateurManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_client', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Coiffeur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_coiffeur', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('est_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coiffeur',
                'verbose_name_plural': 'Coiffeurs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('CONNEXION_ECHEC', 'Échec de connexion'), ('DECONNEXION', 'Déconnexion'), ('INSCRIPTION', 'Inscription'), ('MODIF_PROFIL', 'Modification du profil'), ('MODIF_MOT_DE_PASSE', 'Changement de mot de passe'), ('SUPPRESSION_COMPTE', 'Suppression du compte'), ('COMPTE_VERROUILLE', 'Compte verrouillé')], max_length=30)),
                ('ressource', models.CharField(blank=True, max_length=255)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('succes', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('RESET_MDP', 'Réinitialisation mot de passe'), ('VERIFICATION_EMAIL', 'Vérification email'), ('DEUX_FACTEURS', 'Authentification à deux facteurs')], max_length=30)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token applicatif',
                'verbose_name_plural': 'Tokens applicatifs',
                'ordering': ['-created_at'],
            },
        ),
    ]
