# Generated by Django 6.0.5 on 2026-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('CONNEXION_ECHEC', 'Échec de connexion'), ('DECONNEXION', 'Déconnexion'), ('INSCRIPTION', 'Inscription'), ('MODIF_PROFIL', 'Modification du profil'), ('MODIF_MOT_DE_PASSE', 'Changement de mot de passe'), ('SUPPRESSION_COMPTE', 'Suppression du compte'), ('COMPTE_VERROUILLE', 'Compte verrouillé'), ('ADMIN_RDV_MODIF', 'Modification rendez-vous admin'), ('ADMIN_RDV_ANNULE', 'Annulation rendez-vous admin'), ('ADMIN_RDV_SUSPEND', 'Suspension rendez-vous admin')], max_length=30),
        ),
    ]
