# Generated by Django 6.0.5 on 2026-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateur_photo_utilisateur_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='conditions_reactivation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_demande_reactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_sanction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='motif_sanction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
