# Generated by Django 6.0.5 on 2026-06-02 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('AVERTISSEMENT', 'Avertissement'), ('DANGER', 'Danger'), ('SYSTEME', 'Système')], default='INFO', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-cree_le'],
            },
        ),
    ]
