# Generated by Django 6.0.5 on 2026-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_utilisateur_conditions_reactivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
